name: voice_assistant
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  speech_to_text: ^6.6.1
  http: ^1.2.1
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/virtualAssistant.png
    - assets/sounds/speech_to_text_cancel.m4r
    - assets/sounds/speech_to_text_listening.m4r
    - assets/sounds/speech_to_text_stop.m4r
  fonts:
    - family: Cera-Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf
